# Generated by Django 2.2.2 on 2020-03-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Power',
            field=models.TextField(null=True),
        ),
    ]
