# Generated by Django 2.2.2 on 2020-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_user_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Mark',
            field=models.TextField(null=True),
        ),
    ]
